default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { } %>
  username: <%= ENV.fetch("POSTGRES_USER") { } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB") { } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { } %>
